posts/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'posts'

urlpatterns = [
    # post views
    path("", views.post_list, name="post_list"),
    path("tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    # path('', views.PostListView.as_view(), name='post_list'),
    path("<uuid:uuid>/", views.post_detail, name="post_detail"),
    path("<uuid:post_uuid>/share/", views.post_share, name="post_share"),
    path("<uuid:post_uuid>/comment/", views.post_comment, name="post_comment"),
    path("feed/", LatestPostsFeed(), name="post_feed"),
    path("search/", views.post_search, name="post_search"),
]

scribly/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from posts.sitemaps import PostSitempa


sitemaps = {
    'posts': PostSitempa,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('posts.urls', namespace='posts')),
    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap',
    )
]

templates/base.html
{# templates/base.html #} 
{% load blog_tags %} 
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}My Blog{% endblock title %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet" />
    <link href="{% static 'css/components.css' %}" rel="stylesheet" />
    <link href="{% static 'css/posts.css' %}" rel="stylesheet" />
    <link href="{% static 'css/forms.css' %}" rel="stylesheet" />
    <link href="{% static 'css/comments.css' %}" rel="stylesheet" />
    <link href="{% static 'css/share.css' %}" rel="stylesheet" />
  </head>
  <body>
    <header class="site-header">
      <div class="container">
        <nav>
          <a href="{% url 'posts:post_list' %}" class="site-title">My Blog</a>
          <form method="get" action="{% url 'posts:post_search' %}" class="search-form">
            <input type="text" name="query" placeholder="Search posts..." class="search-input" />
            <button type="submit" class="search-button">
              <i class="fas fa-search"></i>
            </button>
          </form>
        </nav>
      </div>
  </header>

    <div class="container">
      <div class="main-content">
        <main>{% block content %} {% endblock content %}</main>

        <aside class="sidebar">
          <h2>My Blog</h2>
          <p>This is my blog.</p>

          <div class="subscription-section">
            <a href="{% url 'posts:post_feed' %}" class="rss-feed-link">Subscribe to my RSS feed</a>
          </div>

          {% block sidebar %} {% endblock sidebar %}
        </aside>
      </div>
    </div>

    <footer class="site-footer">
      <span class="post-count"> Total Published Posts: {% total_posts %} </span>
      <div class="container">
        <p>&copy; {% now "Y" %} My Blog. All rights reserved.</p>
      </div>
    </footer>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if posts.has_previous %}
            <a href="?page={{ posts.previous_page_number }}">&laquo; Previous</a>
        {% endif %}

        <span class="current">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
        </span>

        {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}">Next &raquo;</a>
        {% endif %}
    </span>
</div>